/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */
    // Include 'plugins build' to define convention plugins.
    //includeBuild("build-logic")
    // Use the plugin portal to apply community plugins in convention plugins.

pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        google()
    }
}


rootProject.name = "spring-boot-gradle-microservices"

include("message")
include("accounts")
include("cards")
include("configserver")
include("loans")
include("gatewayserver")

